# Generated by Django 3.1.5 on 2021-01-08 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210108_1222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
